# Technique Data Cleaning

In [273]:
import pandas as pd

# load csv = messy_customer_data

In [274]:
df = pd.read_csv(r'C:\Users\Muhammad Yahya\Downloads\python\Pandas\Data Cleaning\messy_customer_data.csv')
print('messy_customer_data')
df

messy_customer_data

   Customer_ID       Name  Age       City  Spent_Amount   Join_Date
0          101      Ahmed   25    Karachi        5000.0  2023-01-01
1          102       Sara   30     Lahore        7000.0  2023-01-05
2          103       Zain   22  Islamabad           NaN  2023-01-10
3          101      Ahmed   25    Karachi        5000.0  2023-01-01
4          105     Fatima   28    karachi       12000.0  2023-02-01
5          106    Usman     35     Lahore        8500.0  2023-02-15
6          107      Hamza  250   Peshawar        9000.0  2023-03-01
7          108        NaN   29     Quetta        6000.0  2023-03-05

# Check Missing Values:

In [275]:
df.isnull().sum()

Customer_ID     0
Name            1
Age             0
City            0
Spent_Amount    1
Join_Date       0
dtype: int64

# Spent_Amount: Missing values ko mean() sy fill

In [276]:
df['Spent_Amount'].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: Spent_Amount, dtype: bool

In [277]:
df.loc[2 , 'Spent_Amount'] = df['Spent_Amount'].mean()
df

   Customer_ID       Name  Age       City  Spent_Amount   Join_Date
0          101      Ahmed   25    Karachi        5000.0  2023-01-01
1          102       Sara   30     Lahore        7000.0  2023-01-05
2          103       Zain   22  Islamabad        7500.0  2023-01-10
3          101      Ahmed   25    Karachi        5000.0  2023-01-01
4          105     Fatima   28    karachi       12000.0  2023-02-01
5          106    Usman     35     Lahore        8500.0  2023-02-15
6          107      Hamza  250   Peshawar        9000.0  2023-03-01
7          108        NaN   29     Quetta        6000.0  2023-03-05

# City: karachi (small) ko Karachi (Capital) banana hai.

In [278]:
df['City'] = df['City'].str.capitalize()
df

   Customer_ID       Name  Age       City  Spent_Amount   Join_Date
0          101      Ahmed   25    Karachi        5000.0  2023-01-01
1          102       Sara   30     Lahore        7000.0  2023-01-05
2          103       Zain   22  Islamabad        7500.0  2023-01-10
3          101      Ahmed   25    Karachi        5000.0  2023-01-01
4          105     Fatima   28    Karachi       12000.0  2023-02-01
5          106    Usman     35     Lahore        8500.0  2023-02-15
6          107      Hamza  250   Peshawar        9000.0  2023-03-01
7          108        NaN   29     Quetta        6000.0  2023-03-05

# Name:  Usman  ke agay peeche ki faltu spaces strip() karni hain.

In [279]:
df.loc[5 , 'Name']

'  Usman  '

In [280]:
df.loc[5 , 'Name'] = df.loc[5 , 'Name'].strip()
df

   Customer_ID    Name  Age       City  Spent_Amount   Join_Date
0          101   Ahmed   25    Karachi        5000.0  2023-01-01
1          102    Sara   30     Lahore        7000.0  2023-01-05
2          103    Zain   22  Islamabad        7500.0  2023-01-10
3          101   Ahmed   25    Karachi        5000.0  2023-01-01
4          105  Fatima   28    Karachi       12000.0  2023-02-01
5          106   Usman   35     Lahore        8500.0  2023-02-15
6          107   Hamza  250   Peshawar        9000.0  2023-03-01
7          108     NaN   29     Quetta        6000.0  2023-03-05

In [281]:
df.loc[5,'Name']

'Usman'

# Last Name = NAN ---> fill 0

In [282]:

df['Name'] = df['Name'].fillna(0)
df

   Customer_ID    Name  Age       City  Spent_Amount   Join_Date
0          101   Ahmed   25    Karachi        5000.0  2023-01-01
1          102    Sara   30     Lahore        7000.0  2023-01-05
2          103    Zain   22  Islamabad        7500.0  2023-01-10
3          101   Ahmed   25    Karachi        5000.0  2023-01-01
4          105  Fatima   28    Karachi       12000.0  2023-02-01
5          106   Usman   35     Lahore        8500.0  2023-02-15
6          107   Hamza  250   Peshawar        9000.0  2023-03-01
7          108       0   29     Quetta        6000.0  2023-03-05

In [283]:
df.head()

   Customer_ID    Name  Age       City  Spent_Amount   Join_Date
0          101   Ahmed   25    Karachi        5000.0  2023-01-01
1          102    Sara   30     Lahore        7000.0  2023-01-05
2          103    Zain   22  Islamabad        7500.0  2023-01-10
3          101   Ahmed   25    Karachi        5000.0  2023-01-01
4          105  Fatima   28    Karachi       12000.0  2023-02-01

In [284]:
df.tail()

   Customer_ID    Name  Age      City  Spent_Amount   Join_Date
3          101   Ahmed   25   Karachi        5000.0  2023-01-01
4          105  Fatima   28   Karachi       12000.0  2023-02-01
5          106   Usman   35    Lahore        8500.0  2023-02-15
6          107   Hamza  250  Peshawar        9000.0  2023-03-01
7          108       0   29    Quetta        6000.0  2023-03-05

# Drop Duplicated

In [285]:
df.drop_duplicates(inplace=True)
df

   Customer_ID    Name  Age       City  Spent_Amount   Join_Date
0          101   Ahmed   25    Karachi        5000.0  2023-01-01
1          102    Sara   30     Lahore        7000.0  2023-01-05
2          103    Zain   22  Islamabad        7500.0  2023-01-10
4          105  Fatima   28    Karachi       12000.0  2023-02-01
5          106   Usman   35     Lahore        8500.0  2023-02-15
6          107   Hamza  250   Peshawar        9000.0  2023-03-01
7          108       0   29     Quetta        6000.0  2023-03-05

# Outlier Handle

In [286]:
df.loc[df['Age'] > 100, 'Age'] = 28

In [287]:
print('After_Cleaning_Messy_Customer_Data')
df

After_Cleaning_Messy_Customer_Data

   Customer_ID    Name  Age       City  Spent_Amount   Join_Date
0          101   Ahmed   25    Karachi        5000.0  2023-01-01
1          102    Sara   30     Lahore        7000.0  2023-01-05
2          103    Zain   22  Islamabad        7500.0  2023-01-10
4          105  Fatima   28    Karachi       12000.0  2023-02-01
5          106   Usman   35     Lahore        8500.0  2023-02-15
6          107   Hamza   28   Peshawar        9000.0  2023-03-01
7          108       0   29     Quetta        6000.0  2023-03-05

# clean data store csv

In [289]:
df.to_csv('After_Cleaning_customer_data.csv' , index=False)